# This is a basic workflow to help you get started with Actions

name: Test Github Action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ custom-aciton ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get last commit message
        id: git_message
        uses: ./.github/actions/github-commit-message

      - name: Bot send message
        uses: ./.github/actions/tg-bot-message
        with:
          message: ${{ format('Deployed! "{0}"', steps.git_message.outputs.last_commit_message) }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
